---

- name: Añadir key de sury.org
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  become: yes

- name: Añadir una fuente nueva para el php7.4 (sacado de los docs de Ansible)
  ansible.builtin.apt_repository:
    repo: deb http://packages.sury.org/php/ buster main
    state: present
  become: yes

- name: Hacer un 'apt update' para actualizar los repos (de los docs de Ansible)
  apt:
    name: "*"
    state: latest
  become: yes

- name: Instalar PHP meta
  apt: 
    name: php7.4
    state: latest
  become: yes

- name: Instalar libapache2-mod-php7.4
  apt: 
    name: libapache2-mod-php7.4
    state: latest
  become: yes 


- name: Instalar php7.4-curl
  apt: 
    name: php7.4-curl
    state: latest
  become: yes

- name: Instalar php7.4-mysql
  apt: 
    name: php7.4-mysql
    state: latest
  become: yes

- name: Instalar php7.4-bcmath
  apt: 
    name: php7.4-bcmath
    state: latest
  become: yes

- name: Instalar php7.4-imagick
  apt:
    name: php7.4-imagick
    state: latest
  become: yes

- name: Instalar php-gd
  apt:
    name: php7.4-gd
    state: latest
  become: yes

- name: Instalar php-mbstring
  apt:
    name: php7.4-mbstring
    state: latest
  become: yes

- name: Instalar php xml
  apt:
    name: php7.4-xml
    state: latest
  become: yes

- name: Instalar php zip
  apt:
    name: php7.4-zip
    state: latest
  become: yes

