--
- name: Instalar PHP y módulos necesarios
  apt: name=php7.4 state=latest
  become: yes

- name: Añadir una fuente nueva para el php7.4
  lineinfile: dest=/etc/apt/sources.list.d/php-sury.org.list line="deb http://packages.sury.org/php/ buster main"
  become: yes

- name: Añadir key de sury.org
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

[PENDIENTE] 
